title="output style and description"

# gitlab version with risk
[version]

# admin setting
[settings]
[settings.password]
check_rule="密码复杂度检测"
keyword=true
description="密码复杂度检测"
advice="密码复杂度检测"
[settings.password.length]
check_rule="最小长度"
keyword=true
description="最小长度"
advice="要求数字"
[settings.password.num]
check_rule="要求数字"
keyword=true
check_rule_en="password_require_num"
description="要求数字"
advice="要求数字"
[settings.password.upper]
check_rule="要求大写字母"
keyword=true
description="要求大写字母"
advice="要求大写字母"
[settings.password.lower]
check_rule="要求小写字母"
keyword=true
description="要求大写字母"
advice="要求大写字母"
[settings.password.special]
check_rule="要求特殊符号"
keyword=true
description="要求大写字母"
advice="要求大写字母"

[settings.two_factor_auth]
check_rule="双因素认证"
keyword=true
description="双因素认证描述"
advice="双因素认证建议"

[settings.register]
[settings.register.register_enable]
check_rule="禁用注册功能"
keyword=true
description="此项为true则为禁用用户注册，为false是允许用户注册。"
advice="禁用注册功能建议"
[settings.register.email_confirmation]
check_rule="启用邮箱验证"
keyword=true
description="启用邮箱验证描述"
advice="启用邮箱验证建议"
[settings.register.admin_approval]
check_rule="新用户注册后需等待admin批准"
keyword=true
description="新用户注册后需等待admin批准描述"
advice="新用户注册后需等待admin批准建议"
[settings.register.external]
check_rule="注册区分外部、内部用户"
keyword=true
description="注册区分外部、内部用户描述"
advice="注册区分外部、内部用户建议"
[settings.register.email_regexp_internal]
check_rule="邮箱正则匹配内部用户"
keyword=true
description="邮箱正则匹配内部用户描述"
advice="邮箱正则匹配内部用户建议"

[settings.init_project_enable_default_branch_protection]
check_rule="初始化的项目启用默认分支保护"
keyword=2
description="初始化的项目启用默认分支保护描述"
advice="初始化的项目启用默认分支保护建议"

[settings.web_session_expire]
check_rule="用户登录web页面会话存活时间"
description="用户登录web页面会话存活时间描述"
advice="用户登录web页面会话存活时间建议"

[settings.forbid_create_public_project]
check_rule="禁止建立public项目"
keyword="禁止更改可见性为public"
description="禁止建立public项目描述"
advice="禁止建立public项目保护建议"


[settings.pat_expire]
check_rule="PAT(个人访问令牌)最大生存时间"
description="PAT(个人访问令牌)最大生存时间描述"
advice="PAT(个人访问令牌)最大生存时间建议"

[user.inactive]
check_rule="统计不活跃用户"
description="统计不活跃用户描述"
advice="统计不活跃用户建议"

[user.unactive]
check_rule="统计未启用账户"
description="统计未启用账户描述"
advice="统计未启用账户建议"

[user.two_factor_auth]
check_rule="统计开启双因素认证用户数量"
description="统计开启双因素认证用户数量描述"
advice="统计开启双因素认证用户数量建议"

[user.admin]
check_rule="统计admin数量"
description="统计admin数量描述"
advice="统计admin数量建议"

[user.auditor]
check_rule="统计审计人员数量"
description="统计审计人员数量描述"
advice="统计审计人员数量建议"

[user.external]
check_rule="统计外部用户数量"
description="统计外部用户数量描述"
advice="统计外部用户数量建议"


[output_title]
check_rule="系统及用户基线检查项"
second_check_rule="二级检查项"
result="扫描结果"
keyword="阈值"
complaince="合规情况"
description="说明"
advice="建议"